{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sub2api.fullname" . }}
  labels:
    {{- include "sub2api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- else }}
  DATABASE_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- else }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
  {{- end }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_EXPIRE_HOUR: {{ .Values.secrets.jwtExpireHour | quote }}
  TOTP_ENCRYPTION_KEY: {{ .Values.secrets.totpEncryptionKey | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  {{- if .Values.secrets.geminiOAuthClientID }}
  GEMINI_OAUTH_CLIENT_ID: {{ .Values.secrets.geminiOAuthClientID | quote }}
  {{- end }}
  {{- if .Values.secrets.geminiOAuthClientSecret }}
  GEMINI_OAUTH_CLIENT_SECRET: {{ .Values.secrets.geminiOAuthClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.geminiCliOAuthClientSecret }}
  GEMINI_CLI_OAUTH_CLIENT_SECRET: {{ .Values.secrets.geminiCliOAuthClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.antigravityOAuthClientSecret }}
  ANTIGRAVITY_OAUTH_CLIENT_SECRET: {{ .Values.secrets.antigravityOAuthClientSecret | quote }}
  {{- end }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
