DROP TABLE IF EXISTS ops_system_log_cleanup_audits CASCADE;
DROP TABLE IF EXISTS ops_system_logs CASCADE;
DROP TABLE IF EXISTS ops_alert_silences CASCADE;
DROP TABLE IF EXISTS ops_alert_events CASCADE;
DROP TABLE IF EXISTS ops_alert_rules CASCADE;
DROP TABLE IF EXISTS ops_job_heartbeats CASCADE;
DROP TABLE IF EXISTS ops_system_metrics CASCADE;
DROP TABLE IF EXISTS ops_metrics_daily CASCADE;
DROP TABLE IF EXISTS ops_metrics_hourly CASCADE;
